name: splitbalance
description: A Flutter app for managing shared bills with Google Drive storage.
publish_to: 'none'
version: 0.2.7+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  google_sign_in: ^6.2.1
  googleapis: ^11.3.0
  googleapis_auth: ^1.4.1
  csv: ^5.0.2
  path_provider: ^2.1.1
  intl: any
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
